### PR TITLE
Make remaining Migrations commands out-of-process

### LINKED ISSUE #231: Make EF NuGet package / migrations and EF Tools work with new csproj format
**Workaound:**

Currently the following workaround works (tested on an ASP.NET Core 2.0 app):
- Move the model into a traditional .NET Framework library that uses the old project system
- Add the aforementioned library as a dependency
- Unload the ASP.NET Core application from the solution
- Execute the Enable-migrations command against the library project. This step seems to only be necessary the first time, otherwise you will get an error saying: 
   > Exception calling "SetData" with "2" argument (s): "Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable."
- Re-load the ASP.NET Core project
- Work as normal, with migration commands always pointing to the .NET Framework library project

**Options:**

We could consider
1. Doing the full work to enable EF6 migrations to work with the new project system (which would likely be very expensive)
2. Improve EF6 migrations to handle the presence of projects using the new project system more gracefully, e.g.:
   1. It would be nice if we provided a nice error which provided guidance on creating a separate project
   2. Once a customer applies the workaround, it would be nice if they didn't need to unload the ASP.NET Core project

**Original issue:**

See https://github.com/aspnet/EntityFramework6/issues/230 and https://github.com/aspnet/EntityFramework6/issues/189 and https://github.com/NuGet/Home/issues/4876 

See also _New csproj format and GenerateSeparateFiles=true causes VS2017 to freeze  https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/266_ which blocks EF Tools tt codegen with the new csproj files.

### PR DESCRIPTION
**Pull request by bricelam**
Note, this removes migrate.exe; it has been superseded by ef6.exe

Resolves #231

### CODE REVIEW

File: src/EntityFramework/Migrations/Design/ToolingFacade.cs [hunk 1]
```diff
@@ -27,7 +27,7 @@ namespace System.Data.Entity.Migrations.Design
     /// The App/Web.config file from the startup project is also copied
     /// to ensure that any configuration is applied.
     /// </summary>
-    // TODO: Move this functionality to System.Data.Entity.Infrastructure.Design.Executor
+    [Obsolete("Use System.Data.Entity.Infrastructure.Design.Executor instead.")]
```
Comment (bricelam) [inline src/EntityFramework/Migrations/Design/ToolingFacade.cs]: ❤
